name: Deploy AVM KeyVault Module

on:
  workflow_dispatch:

env:
  ACR_NAME: avmmodulestf.azurecr.io
  MODULE_VERSION: 0.1.0
  RESOURCE_GROUP: example-rg
  LOCATION: westeurope

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Install ORAS
        run: |
          curl -LO https://github.com/oras-project/oras/releases/download/v1.1.0/oras_1.1.0_linux_amd64.tar.gz
          tar -zxvf oras_1.1.0_linux_amd64.tar.gz oras
          sudo mv oras /usr/local/bin/oras
          hash -r  # <- THIS forces shell to reload the available binaries immediately

      - name: Check ORAS version (force your version)
        run: |
          oras version

      - name: Download KeyVault module from ACR
        run: |
          mkdir -p modules/avm-res-keyvault-vault
          oras pull ${{ env.ACR_NAME }}/avm-res-keyvault-vault/azurerm:${{ env.MODULE_VERSION }} -o modules/avm-res-keyvault-vault

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
